# Generated by Django 5.0.4 on 2024-04-23 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipes',
            old_name='recepies_image',
            new_name='receipe_image',
        ),
    ]
